
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    - run: R CMD build .

    - run: docker pull kalibera/rchk:latest
    - run: |
          mkdir -p rchk/packages
          mv reticulate_*.tar.gz rchk/packages/
          cd rchk/packages
          pkgtar=$(ls reticulate_*.tar.gz)
          docker run -v `pwd`/packages:/rchk/packages kalibera/rchk:latest /rchk/packages/$pkgtar
